<?php

function authorize_forms_page_attachments(array &$page) {

    $current_uri = \Drupal::request()->getRequestUri();
    // Get vars from config
    $config = \Drupal::config('authorize_forms.settings');

    if(strpos($current_uri,$config->get('payment_forms_url').'/') !== false){

        $mode = $config->get('mode');
        if($mode == 'sandbox'){
            $scriptURL = 'https://jstest.authorize.net/v1/Accept.js';
        }else{
            $scriptURL = 'https://js.authorize.net/v1/Accept.js';
        }

        // Add accept.js to head as drupal strips https out of URL on libraries
        $script = [
            '#tag' => 'script',
            '#attributes' => [
                'src' => $scriptURL,
            ],
        ];
        $page['#attached']['html_head'][] = [$script, 'script'];

        // Add functionality script library
        $page['#attached']['library'][] = 'authorize_forms/scripts';

    }

}