<?php

function authorize_forms_page_attachments(array &$page) {

    $current_uri = \Drupal::request()->getRequestUri();

    if(strpos($current_uri,'payment/') !== false){

        // Add accept.js to head as drupal strips https out of URL on libraries
        $script = [
            '#tag' => 'script',
            '#attributes' => [
                'src' => 'https://js.authorize.net/v1/Accept.js',
            ],
        ];
        #https://js.authorize.net/v1/Accept.js
        $page['#attached']['html_head'][] = [$script, 'script'];

        // Add functionality script library
        $page['#attached']['library'][] = 'authorize_forms/scripts';

    }

}