authorize_forms.settings:
  type: config_object
  label: 'Authorize.net Settings'
  mapping:
    api_login_id:
      type: string
    transaction_key:
      type: string
    public_client_key:
      type: string